{"name": "Ручка /api/v1/orders/accept/", "status": "passed", "description": "Создаём заказ, получаем трек номер, принимаем заказ с некорректным id курьера", "start": 1710612773889, "stop": 1710612774009, "uuid": "2c61341b-8681-4f93-8971-8ed561b5a767", "historyId": "a880846fcbfb59b7d59484d90ca1336b", "testCaseId": "a880846fcbfb59b7d59484d90ca1336b", "fullName": "test_api.tests.test_accept_order.TestAcceptOrder#test_accept_order_wrong_courier_id_error", "labels": [{"name": "parentSuite", "value": "test_api.tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "LAPTOP-KS9V29SF"}, {"name": "thread", "value": "24912-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api.tests.test_accept_order"}]}