{"name": "test_take_order_number_wrong_number_error", "status": "passed", "description": "Получаем заказ по неправильному номеру", "start": 1710094599235, "stop": 1710094599352, "uuid": "1117b14b-7c07-4c81-b313-1bc9498e1436", "historyId": "4435357238e942382346d827b7e6ab17", "testCaseId": "4435357238e942382346d827b7e6ab17", "fullName": "test_api.tests.test_take_order_number.TestTakeOrderNumber#test_take_order_number_wrong_number_error", "labels": [{"name": "parentSuite", "value": "test_api.tests"}, {"name": "suite", "value": "test_take_order_number"}, {"name": "subSuite", "value": "TestTakeOrderNumber"}, {"name": "host", "value": "LAPTOP-KS9V29SF"}, {"name": "thread", "value": "38908-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api.tests.test_take_order_number"}]}