{"name": "test_accept_order_wrong_track_number_error", "status": "passed", "description": "Создаём курьера, логинимся, принимаем заказ с несуществующим id", "start": 1710094437059, "stop": 1710094437280, "uuid": "52091c94-8e5c-4e58-8a30-b9a941ab7fde", "historyId": "36cdde27c4f93e161758ac1bc29300c7", "testCaseId": "36cdde27c4f93e161758ac1bc29300c7", "fullName": "test_api.tests.test_accept_order.TestAcceptOrder#test_accept_order_wrong_track_number_error", "labels": [{"name": "parentSuite", "value": "test_api.tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "LAPTOP-KS9V29SF"}, {"name": "thread", "value": "38908-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api.tests.test_accept_order"}]}