{"name": "Ручка /api/v1/orders/accept/", "status": "passed", "description": "Создаём курьера, логинимся, принимаем заказ с несуществующим id", "start": 1710617468163, "stop": 1710617468213, "uuid": "56a0a317-d24e-4bd1-b99b-5ce31948c67d", "historyId": "36cdde27c4f93e161758ac1bc29300c7", "testCaseId": "36cdde27c4f93e161758ac1bc29300c7", "fullName": "test_api.tests.test_accept_order.TestAcceptOrder#test_accept_order_wrong_track_number_error", "labels": [{"name": "parentSuite", "value": "test_api.tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "LAPTOP-KS9V29SF"}, {"name": "thread", "value": "5592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api.tests.test_accept_order"}]}