{"name": "Ручка /api/v1/courier/login", "status": "passed", "description": "Создаём нового курьера, затем логинимся с неправильным логином, ожадаем ошибку 404 и сообщение 'Учетная запись не найдена'", "start": 1710444269063, "stop": 1710444269203, "uuid": "0a2aac6f-6222-48c8-a41b-213ce82f798d", "historyId": "7674ec18c973a31a591397398ab64cf7", "testCaseId": "7674ec18c973a31a591397398ab64cf7", "fullName": "test_api.tests.test_login_courier.TestLoginCourier#test_login_courier_wrong_login", "labels": [{"name": "parentSuite", "value": "test_api.tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "LAPTOP-KS9V29SF"}, {"name": "thread", "value": "23240-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api.tests.test_login_courier"}]}