{"name": "Ручка /api/v1/courier/login", "status": "passed", "description": "Логинимся с неправильным логином, ожидаем ошибку 404 и сообщение 'Учетная запись не найдена'", "start": 1710612933699, "stop": 1710612933809, "uuid": "6b03a3b2-d2ba-4968-8e43-c52faab00942", "historyId": "7674ec18c973a31a591397398ab64cf7", "testCaseId": "7674ec18c973a31a591397398ab64cf7", "fullName": "test_api.tests.test_login_courier.TestLoginCourier#test_login_courier_wrong_login", "labels": [{"name": "parentSuite", "value": "test_api.tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "LAPTOP-KS9V29SF"}, {"name": "thread", "value": "24912-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api.tests.test_login_courier"}]}