{"name": "Ручка /api/v1/orders/accept/", "status": "passed", "description": "Создаём заказ, получаем трек номер, принимаем заказ с некорректным id курьера", "steps": [{"name": "Получение трек-номера заказа", "status": "passed", "start": 1710620268883, "stop": 1710620268883}, {"name": "Запрос на принятие заказа по трек-номеру и некорректному ID курьера", "status": "passed", "start": 1710620268883, "stop": 1710620268925}, {"name": "Проверки на статус и ответ", "status": "passed", "start": 1710620268925, "stop": 1710620268925}], "start": 1710620268883, "stop": 1710620268925, "uuid": "2332e999-7cad-4c70-962b-d7c4093b7d3c", "historyId": "a880846fcbfb59b7d59484d90ca1336b", "testCaseId": "a880846fcbfb59b7d59484d90ca1336b", "fullName": "test_api.tests.test_accept_order.TestAcceptOrder#test_accept_order_wrong_courier_id_error", "labels": [{"name": "parentSuite", "value": "test_api.tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "LAPTOP-KS9V29SF"}, {"name": "thread", "value": "23412-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api.tests.test_accept_order"}]}