{"name": "Ручка /api/v1/orders/accept/", "status": "passed", "description": "Создаём курьера, логинимся, принимаем заказ с несуществующим id", "steps": [{"name": "Создание нового курьера и получение его ID", "status": "passed", "start": 1710620268659, "stop": 1710620268659}, {"name": "Запрос на принятие заказа по неправильному трек-номеру и ID курьера", "status": "passed", "start": 1710620268659, "stop": 1710620268739}, {"name": "Проверки на статус и ответ", "status": "passed", "start": 1710620268739, "stop": 1710620268739}], "start": 1710620268659, "stop": 1710620268739, "uuid": "fbd4a1f0-6f4c-416f-9a20-25f361b7b405", "historyId": "36cdde27c4f93e161758ac1bc29300c7", "testCaseId": "36cdde27c4f93e161758ac1bc29300c7", "fullName": "test_api.tests.test_accept_order.TestAcceptOrder#test_accept_order_wrong_track_number_error", "labels": [{"name": "parentSuite", "value": "test_api.tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "LAPTOP-KS9V29SF"}, {"name": "thread", "value": "23412-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api.tests.test_accept_order"}]}