{"name": "Ручка /api/v1/orders/track", "status": "passed", "description": "Получаем заказ по неправильному номеру", "start": 1710617630203, "stop": 1710617630303, "uuid": "7b491528-b88f-44b0-a052-6490c12430bb", "historyId": "4435357238e942382346d827b7e6ab17", "testCaseId": "4435357238e942382346d827b7e6ab17", "fullName": "test_api.tests.test_take_order_number.TestTakeOrderNumber#test_take_order_number_wrong_number_error", "labels": [{"name": "parentSuite", "value": "test_api.tests"}, {"name": "suite", "value": "test_take_order_number"}, {"name": "subSuite", "value": "TestTakeOrderNumber"}, {"name": "host", "value": "LAPTOP-KS9V29SF"}, {"name": "thread", "value": "5592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api.tests.test_take_order_number"}]}