{"name": "test_accept_order_wrong_courier_id_error", "status": "passed", "description": "Создаём заказ, получаем трек номер, принимаем заказ с некорректным id курьера", "start": 1710094437282, "stop": 1710094437421, "uuid": "fc4f0cf3-6e4a-4874-bad5-83f4b9156c54", "historyId": "a880846fcbfb59b7d59484d90ca1336b", "testCaseId": "a880846fcbfb59b7d59484d90ca1336b", "fullName": "test_api.tests.test_accept_order.TestAcceptOrder#test_accept_order_wrong_courier_id_error", "labels": [{"name": "parentSuite", "value": "test_api.tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "LAPTOP-KS9V29SF"}, {"name": "thread", "value": "38908-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api.tests.test_accept_order"}]}